# Generated by Django 3.2.6 on 2021-08-03 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 23, 25, 3, 151861)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 23, 25, 3, 149833)),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 23, 25, 3, 150863)),
        ),
    ]
