# Generated by Django 3.2.6 on 2021-08-03 21:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0002_auto_20210803_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='account',
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 0, 52, 11, 948162)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 0, 52, 11, 948162)),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 0, 52, 11, 948162)),
        ),
    ]
