# Generated by Django 3.2.6 on 2021-08-04 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20210804_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 4, 11, 25, 986329)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 4, 11, 25, 984373)),
        ),
        migrations.AlterField(
            model_name='post',
            name='deleting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 4, 4, 11, 25, 985322)),
        ),
    ]
