# Generated by Django 3.2.6 on 2021-08-03 01:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 4, 18, 37, 517508))),
                ('posting_date', models.DateTimeField()),
                ('deleting_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[(1, 'Like'), (2, 'Dislike'), (3, 'None')], default=3, max_length=200)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 4, 18, 37, 518724))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.account')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(1, 'Owner'), (2, 'Admin'), (3, 'Editor'), (4, 'None')], default=4, max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.account')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.post')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 4, 18, 37, 521716))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.account')),
            ],
        ),
    ]
